[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "seg_cave_paintings"
version = "0.1.0"
description = "Useful functions for segmentation of cave paintings, including preprocessing steps and implementation of Otsu thresholding, Meanshift, and active contours methods."
authors = [
  {name = "Manon Arfib, Louisa Arfib"}
]
dependencies = []